name: deploy

on:
  push:
    branches:
      - main
      - master
      - develop

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_API_KEY }}
  PROJECT_ID: 'model-twiiter'

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn generate
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --project ${PROJECT_ID} --token ${FIREBASE_TOKEN} --only hosting
